app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('clone.urls')),
]

clone/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('create/', views.create, name='create'),
    path('comment/<int:id>/', views.comment, name='comment'),
    path('like/', views.like, name="like"),
    path('profile/<int:id>/', views.profile, name="profile"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('register/', views.register, name='register'),
    path('single/<int:id>/', views.single, name='single'),
]

clone/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User

# Create your models here.


#Choices
LIKE_CHOICE = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profilePhoto = CloudinaryField('image')
    bio = models.TextField(max_length=200, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.user)
    
    def num_image(self):
        return self.profile.all().count()
    
    
        
    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()

    def update(self, profilePhoto, bio):
        self.bio = bio
        self.profilePhoto = profilePhoto
        self.save()

class Image(models.Model):
    image = CloudinaryField('image')
    name = models.CharField(max_length=20)
    caption = models.TextField()
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user',null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='profile',null=True)
    
    
    class Meta:
        ordering = ['-updated','-created']
    
    def __str__(self):
        return self.name 
    
    def num_likes(self):
        return self.liked.all().count()
    
    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    def update_caption(self, caption, name):
        self.caption = caption
        self.name = name
        self.save()
    

    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICE,default='Like',max_length=10)
    
    def __str__(self):
        return self.image
    
    
class Comment(models.Model):
    image = models.ForeignKey(Image, related_name="comments",on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=50, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.image.name

clone/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Image, Comment, Profile


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['image','name','caption']
        
        
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['profilePhoto','bio']

class SearchForm(forms.Form):
    name = forms.CharField(max_length=30)

clone/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm, ImageForm, CommentForm, ProfileForm, SearchForm
from .models import Image, Comment, Profile
# Create your views here.

#Landing Page
@login_required(login_url='login')
def index(request):
    posts = Image.objects.all()
    form = CommentForm()
    searchform = SearchForm()
    userid = request.user.id
    if request.method == 'POST':
        searchform = SearchForm(request.POST)
        if searchform.is_valid():
            name = searchform.cleaned_data['name']
            profile = Profile.objects.get(user__username=name)
            userid = request.user.id
            return render(request, 'app/profile.html',{"profile":profile, "userid":userid})
    return render(request, 'app/index.html',{"title":"Home","posts":posts,"form":form,"userid":userid,"searchform":searchform})

#Register Form
def register(request):
    form = RegisterForm()
    userid = request.user.id
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    
    return render(request, 'registration/register.html', {"form":form, "userid":userid})

def profile(request, id):
    profile = Profile.objects.get(user=id)
    userid = request.user.id

    return render(request, 'app/profile.html',{"profile":profile, "userid":userid})


#Create Post Form
@login_required(login_url='login')
def create(request):
    form = ImageForm()
    userid = request.user.id
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']
            name = form.cleaned_data['name']
            caption = form.cleaned_data['caption']
            user_of_post = request.user
            post = Image(image=image,name=name, caption=caption,user=user_of_post,profile=user_of_post.profile)
            post.save()
            return redirect('home')
    return render(request, 'app/create.html', {"form":form,"userid":userid})

#Comment form
def comment(request, id):
    image = Image.objects.get(id=id)
    if request.method == "POST":
        comment = request.POST.get('comment')
        user = request.user
        comment_new = Comment(image=image,name=user, comment=comment)
        comment_new.save()
        return redirect('single',image.id)
    
    
#Like Form
def like(request):
    user = request.user
    if request.method == "POST":
        image_id = request.POST.get('image_id')
        image_obj = Image.objects.get(id=image_id)
        
        if user in image_obj.liked.all():
            image_obj.liked.remove(user)
        else:
            image_obj.liked.add(user)
    return redirect('home')


#Single Form
@login_required(login_url='login')
def single(request, id):

    post = Image.objects.get(id=id)
    form = CommentForm()
    userid = request.user.id
    return render(request, 'app/single.html', {'post':post,"userid":userid,"form":form})




def edit(request, id):
    profile = Profile.objects.get(id=id)
    form = ProfileForm(instance=profile)
    userid = request.user.id
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            # instance.user = Profile.objects.get(user=request.user)
            instance.save()
            return redirect(f'profile/{userid}/')
    return render(request, 'app/edit.html', {"form":form})

insta/templates/instagram/progile.html
{% extends 'instagram/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container" style="margin-top:8%">
    <div class="content-section">
        <div class="media">
            <div class="container">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <img class="rounded-circle account-img" src="{{ user.profile.profile_picture.url }}">
                    </div>
                    <div class="col-md-6 mt-3">
                        <div class="media-body">
                            <div class="account-heading"><span class="mr-3 text-secondary username">{{ user.username }}</span>
                                <a class="btn btn-sm btn-outline-secondary mr-3" data-toggle="modal" data-target=".bd-example-modal-md"><strong>Edit Profile</strong></a>
                                <a class="mt-3" data-toggle="modal" data-target="#ModalCenter"><i class="fa fa-cog mt-3" id="cog"></i></a>
                            </div>

                            <div class="post-details mt-3 mb-3">
                                <span class="mr-5"><strong>{{images.count}}</strong> Posts</span>
                                <span class="mr-5"> <strong>{{ user.profile.followers.count }}</strong> followers</span>
                                <span class="mr-5"> <strong>{{ user.profile.following.count }}</strong> following</span>
                            </div>
                            <h5>{{ user.profile.name }}</h5>
                            <p class="text-secondary">{{ user.profile.bio }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade bd-example-modal-sm" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <a class="D-block mx-auto" href="">Change Password</a>
                        <hr>
                        <a class="D-block mx-auto" href="{% url 'logout' %}">Log Out</a>
                        <hr>
                        <a class="D-block mx-auto" href="" data-dismiss="modal">Close</a>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal fade bd-example-modal-md" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-md ">
                <div class="modal-content">
                    <form action="" method="post" novalidate enctype="multipart/form-data" class="mr-4 mt-4 ml-4 mb-4">
                        {% csrf_token%}
                        {{ user_form|crispy}}
                        {{ prof_form|crispy}}
                        <button type="submit" class="btn btn-primary btn-sm"> Update Profile</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <hr class="mt-4">
    <div class="card-columns">
        {% for image in images %}
            <div class="card">
                <div class="card-body">
                    <img src="{{image.image.url}}" alt="{{image.caption}}" class="card-img">
                    <p id="overlay"class="text"> 
                            <i class="fas fa-heart" style="color:white; font-size: 18"></i> 
                            <span style="color: white">{{image.likes.count}}</span>
                             <i class="fas fa-comment ml-4" style="color: white"></i> <span style="color: white">{{image.comments.count}}</span></p>
                    
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/app/create.html
{% extends 'app/layout.html' %} {% load static %} {% block head %}
<style>
    label {
        display: none;
    }
</style>
<link rel="stylesheet" href="{% static 'css/create.css' %}"> {% endblock %} {% block content %}
<section class="create">
    <article class="create-container">
        <form action="" class="create-form" method="post" enctype=multipart/form-data>
            {% csrf_token %}
            <div class="create-form-title">
                <h1>Create new Post</h1>
            </div>
            <div class="create-form-image">
                {{form.as_p}}
            </div>
            <div class="create-form-submit">
                <button type="submit">Share</button>
            </div>
        </form>
    </article>
</section>
<script>
    $(document).ready(function() {
        $("#id_comment").attr('placeholder', '{{form.comment.label}}');
        $("#id_name").attr('placeholder', '{{form.name.label}}');
        $("#id_caption").attr('placeholder', '{{form.caption.label}}');
    });
</script>
{% endblock %}

templates/app/edit.html
{% extends 'app/layout.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/edit_profile.css' %}"> {% endblock %} {% block content %}
<section class="create">
    <article class="create-container">
        <form action="" class="create-form" method="post" enctype=multipart/form-data>
            {% csrf_token %}
            <div class="create-form-title">
                <h1>Edit Profile</h1>
            </div>
            <div class="create-form-image">
                {{form.as_p}}
            </div>
            <div class="create-form-submit">
                <button type="submit">Update</button>
            </div>
        </form>
    </article>
</section>
{% endblock %}

templates/app/index.html
{% extends 'app/layout.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/post.css' %}"> {% endblock %} {% block content %}
<section class="posts">
    <article class="post-container">
        {% for post in posts %}
        <div class="post">
            <div class="post-user">
                <div class="post-user-image">
                    {% if not post.profile.profilePhoto.url %}
                    <img src="{% static 'images/default.jpg' %}" alt=""> {% else %}
                    <img src="{{ post.profile.profilePhoto.url }}" alt="default"> {% endif %}
                </div>
                <div class="post-user-name">
                    <h1>{{post.user}} --<a href="{% url 'profile' post.user.id %}">Follow</a></h1>
                </div>
            </div>
            <div class="post-image">
                <img src="{{post.image.url}}" alt="pic">
            </div>
            <div class="post-features">
                <form action="{% url 'like' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="image_id" value="{{ post.id }}"> {% if user not in post.liked.all %}
                    <button type="submit"><img src="{% static 'images/heart(4).png' %}" alt=""></button> {% else %}
                    <button type="submit"><img src="{% static 'images/heart(3).png' %}" alt=""></button> {% endif %}
                </form>
                <a href="{% url 'single' post.id %}"><img src="{% static 'images/bubble-chat.png'%}" alt=""></a>
            </div>
            <div class="post-likes">
                {% if image.liked.all.count == 1 %}
                <strong>{{ post.liked.all.count }} like</strong> {% else %}
                <strong>{{ post.liked.all.count }} likes</strong> {% endif %}
            </div>
            <div class="post-title">
                <h4>{{ post.caption }}</h4>
            </div>
            <div class="post-view-comments">
                <p><a href="{% url 'single' post.id %}">View Comments</a></p>
            </div>
            <div class="post-time">
                <p>{{ post.created }}</p>
            </div>
            <div class="post-comment">
                <form action="{% url 'comment' post.id %}" method="post">
                    {% csrf_token %} {{form}}
                    <button type="submit">Post</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </article>
</section>
<script>
    $(document).ready(function() {
        $("#id_comment").attr('placeholder', '{{form.comment.label}}');
    });
</script>
{% endblock %}

templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link rel="icon" href="{% static 'images/instagram.png' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}"> {% if title %}
    <title>Instagram - {{ title }}</title>
    {% else %}
    <title>Instagram</title>
    {% endif %} {% block head %} {% endblock %}
</head>

<body>
    <section class="nav-container">
        <nav class="nav">
            <article class="nav-logo">
                <h1>Instagram</h1>
            </article>
            <article class="nav-search">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="nav-search-image">
                        <img src="{% static 'images/magnifying-glass.png' %}" alt="search">
                    </div>
                    <div class="nav-search-input">
                        {{searchform}}
                    </div>
                </form>
            </article>
            <article class="nav-links">
                <div class="nav-links-home">
                    <a href="{% url 'home' %}"><img src="{% static 'images/homepage.png' %}" alt="home"></a>
                </div>
                <div class="nav-links-create">
                    <a href="{% url 'create' %}"><img src="{% static 'images/more.png'%}" alt="create"></a>
                </div>
                <div class="nav-links-profile">
                    <div>
                        <a href="{% url 'profile' user.id %}">
                            {% if user.id == userid %}
                                {% if not user.profile.profilePhoto.url %}
                            <img src="{% static 'images/default.jpg'%}" alt="profile"> {% else %}
                            <img src="{{user.profile.profilePhoto.url}}" alt="profile"> {% endif %}
                            {% else %}
                            <img src="{% static 'images/default.jpg'%}" alt="profile">
                            {% endif %}
                        </a>
                    </div>
                </div>
            </article>
        </nav>
    </section>
    {% block content %} {% endblock %}
</body>

</html>

templates/app/profile.html
{% extends 'app/layout.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}"> {% endblock %} {% block content %}
<section class="profile">
    <article class="profile-container">
        <div class="profile-image">
            {% if not profile.profilePhoto.url %}
            <img src="{% static 'images/default.jpg'%}" alt="profile"> {% else %}
            <img src="{{profile.profilePhoto.url}}" alt="profile"> {% endif %}
        </div>
        <div class="profile-info">
            <div class="profile-info-name">
                <div class="profile-info-name-username">
                    <h1>{{ profile.user }}</h1>
                </div>
                {% if profile.user.id == userid %}
                <div class="profile-info-name-edit">
                    <button><a href="{% url 'edit' profile.id %}">Edit Profile</a></button>
                    <button><a href="{% url 'logout' %}">Logout</a></button>
                </div>
                {% endif %}
            </div>
            <div class="profile-info-bio">
                <p>{{ profile.bio }}</p>
            </div>
            <div class="profile-info-details">
                <div class="profile-info-details-posts">
                    <p>{{ profile.profile.all.count }} posts</p>
                </div>
                <div class="profile-info-details-followers">
                    <p>0 followers</p>
                </div>
            </div>
        </div>
    </article>
</section>
<section class="user-posts">
    <article class="user-posts-container">
        <div class="user-posts-title">
            <img src="{% static 'images/more.png'%}" alt="posts">
            <h4>Posts</h4>
        </div>
        <ul class="user-posts-posts">
            {% for post in profile.profile.all %}
            <li class="user-posts-posts-li">
                <a href="{% url 'single' post.id %}"><img src="{{post.image.url}}" alt=""></a>
            </li>
            {% endfor %}
        </ul>
    </article>
</section>
{% endblock %}

templates/app/single.html
{% extends 'app/layout.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/create.css' %}">
<link rel="stylesheet" href="{% static 'css/single.css' %}"> {% endblock %} {% block content %}
<section class="post">
    <article class="post-container">
        <div class="post-image">
            <img src="{{ post.image.url }}" alt="">
        </div>
        <div class="post-user">
            <div class="post-user-name">
                {% if user.id == userid %} {% if not user.profile.profilePhoto.url %}
                <img src="{% static 'images/default.jpg'%}" alt="profile"> {% else %}
                <img src="{{user.profile.profilePhoto.url}}" alt="profile"> {% endif %} {% else %}
                <img src="{% static 'images/default.jpg'%}" alt="profile"> {% endif %}
                <h3>{{ post.user.username }}</h3>
            </div>
            <div class="post-likes">
                {% if image.liked.all.count == 1 %}
                <strong>{{ post.liked.all.count }} like</strong> {% else %}
                <strong>{{ post.liked.all.count }} likes</strong> {% endif %}
            </div>
        </div>
        <div class="post-title">
            <p>{{ post.name }}</p>
        </div>
        <div class="post-caption">
            <p>{{ post.caption }}</p>
        </div>
        <div class="post-created">
            <p>{{ post.created }}</p>
        </div>
        <div class="post-comment">
            <form action="{% url 'comment' post.id %}" method="post">
                {% csrf_token %} {{form}}
                <button type="submit">Post</button>
            </form>
        </div>
        <div class="post-comments-title">
            <h1>Comments</h1>
        </div>
        <ul class="post-comment-comments">
            {% for comment in post.comments.all %}
            <li>
                <h3>{{ comment.comment }}</h3>
                <p>--{{ comment.name }}</p>
            </li>
            {% endfor %}

        </ul>
    </article>
</section>
<script>
    $(document).ready(function() {
        $("#id_comment").attr('placeholder', '{{form.comment.label}}');
    });
</script>
{% endblock %}